# Generated by Django 5.2.1 on 2025-06-04 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='files/')),
                ('is_shareable', models.BooleanField(default=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('share_link', models.URLField(blank=True, max_length=600, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
